### ISSUE TITLE
no longer showing preview

### ISSUE THREAD

**Issue by skeddles** [lostintangent/codeswing#101]
idk why but the preview window suddenly stopped working for me 

i restarted computer and reinstalled add on and tried other swings and a new one

![image](https://github.com/user-attachments/assets/e4ee24f6-4135-4e75-a8c2-57893c7cbaa9)

**Comment by mikedpad** [comment]
I'm seeing the same issue. This started after the latest Visual Studio Code update for July 2024 (version 1.92).

**Comment by HDDTHR** [comment]
I think I might be experiencing the same thing myself.
The `CodeSwing` output window is empty, while the  `Extension Host` output window shows this error..

![2024-08-09-09:42:37-screenshot](https://github.com/user-attachments/assets/f130977b-6f8c-4775-b1b1-30c982fc9cf2)

```
2024-08-09 09:35:57.778 [error] TypeError: Cannot convert a Symbol value to a string
	at createAction (.././node_modules/mobx/dist/mobx.esm.js:695:102)
	at action (.././node_modules/mobx/dist/mobx.esm.js:2194:34)
	at makeAction (.././node_modules/mobx/dist/mobx.esm.js:3104:45)
	at makeProperty (.././node_modules/mobx/dist/mobx.esm.js:3171:11)
	at eval (.././node_modules/mobx/dist/mobx.esm.js:2427:7)
	at Array.forEach (<anonymous>)
	at extendObservable (.././node_modules/mobx/dist/mobx.esm.js:2426:31)
	at Function.object (.././node_modules/mobx/dist/mobx.esm.js:627:12)
	at deepEnhancer (.././node_modules/mobx/dist/mobx.esm.js:516:43)
	at new ObservableValue (.././node_modules/mobx/dist/mobx.esm.js:928:20)
	at ObservableObjectAdministration.addObservableProp_ (.././node_modules/mobx/dist/mobx.esm.js:4611:22)
	at makeProperty (.././node_modules/mobx/dist/mobx.esm.js:3218:13)
	at eval (.././node_modules/mobx/dist/mobx.esm.js:2427:7)
	at Array.forEach (<anonymous>)
	at extendObservable (.././node_modules/mobx/dist/mobx.esm.js:2426:31)
	at Function.object (.././node_modules/mobx/dist/mobx.esm.js:627:12)
	at deepEnhancer (.././node_modules/mobx/dist/mobx.esm.js:516:43)
	at new ObservableValue (.././node_modules/mobx/dist/mobx.esm.js:928:20)
	at ObservableObjectAdministration.addObservableProp_ (.././node_modules/mobx/dist/mobx.esm.js:4611:22)
	at set (.././node_modules/mobx/dist/mobx.esm.js:2736:11)
	at Object.set$1 [as set] (.././node_modules/mobx/dist/mobx.esm.js:3019:5)
	at openSwing (.././src/preview/index.ts:269:31)
```
1.92.0-insider
b1c0a14de1414fcdaa400695b4db1c0799bc3124
x64
Arch Linux

**Comment by serhatbek** [comment]
I added the extension yesterday and have the same issue. I disabled all my other extensions to check if anything is interrupting but nothing changed.

**Comment by RogerHolbrook** [comment]
I had the same problem - no output in the CodeSwing window.
With the same error messages in the Extension Host output window as HDDTHR above.  
Running VSCode 1.92.2
Rollback to VScode 1.91 restores output to CodeSwing window.
Windows 11 Pro
Version	23H2
OS build	22631.4037
Windows Feature Experience Pack 1000.22700.1027.0

**Comment by lostintangent** [comment]
This has now been fixed with the latest version of CodeSwing

**Comment by skeddles** [comment]
thanks!
