### ISSUE TITLE
Not able to launch code swing

### ISSUE THREAD

**Issue by rajivharris** [lostintangent/codeswing#40]
```bash
➜ code -v
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
```
Codeswing version : codespaces-contrib.codeswing@0.0.16

When try to create a new code swing **ctrl+shift+P CodeSwing:New Swing** noting happens. Same for the directory option also.

And I see the following error in the Log(Window)
```
[2021-03-09 14:18:49.186] [renderer4] [error] [MobX] minified error nr: 35. Find the full error at: https://github.com/mobxjs/mobx/blob/mobx6/src/errors.ts: Error: [MobX] minified error nr: 35. Find the full error at: https://github.com/mobxjs/mobx/blob/mobx6/src/errors.ts
    at n (c:\Users\ashora4\.vscode\extensions\codespaces-contrib.codeswing-0.0.16\dist\extension.js:2:1590490)
    at Timeout._onTimeout (c:\Users\ashora4\.vscode\extensions\codespaces-contrib.codeswing-0.0.16\dist\extension.js:2:1607968)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[2021-03-09 14:18:50.312] [renderer4] [error] Cannot get the libraries.: Error: Cannot get the libraries.
    at c:\Users\ashora4\.vscode\extensions\codespaces-contrib.codeswing-0.0.16\dist\extension.js:1067:36224
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.t.getCDNJSLibraries (c:\Users\ashora4\.vscode\extensions\codespaces-contrib.codeswing-0.0.16\dist\extension.js:1067:36268)
[2021-03-09 14:18:50.313] [renderer4] [error] Request failed with status code 400: Error: Request failed with status code 400
    at e.exports (c:\Users\ashora4\.vscode\extensions\codespaces-contrib.codeswing-0.0.16\dist\extension.js:2:660111)
    at e.exports (c:\Users\ashora4\.vscode\extensions\codespaces-contrib.codeswing-0.0.16\dist\extension.js:2:662513)
    at IncomingMessage.<anonymous> (c:\Users\ashora4\.vscode\extensions\codespaces-contrib.codeswing-0.0.16\dist\extension.js:2:655092)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by lostintangent** [comment]
This should now be resolved. Let me know if you're running into issues. Thanks!
